version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wordpress/scripts"
    versions:
    - 13.0.1
    - 13.0.2
    - 13.0.3
    - 14.0.0
    - 14.0.1
    - 14.1.0
